package com.example.sheba_mental_health_project.model.enums;

public enum ViewModelEnum {
    MainActivity,
    WelcomeActivity,
    Welcome,
    PatientLogin,
    TherapistLogin,
    PreQuestions,
    Treaty,
    Bureaucracy,
    SanityCheck,
    Statement,
    MainTherapist,
    TherapistPhysicalState,
    TherapistMentalState,
    TherapistMentalGeneric,
    AppointmentTherapist,
    SearchPatient,
    StartMeeting,
    AddAppointment,
    AddPatient,
    MainPatient,
    PreMeetingCharacter,
    AppointmentLounge,
    AppointmentPatient,
    MentalPatient,
    PhysicalPatient,
    Chat,
    Character,
    Head,
    CenterOfMass,
    Back,
    RightArm,
    LeftArm,
    Genitals,
    Legs
}
